### ISSUE TITLE
Using interrupts on digital pins

### ISSUE THREAD

**Issue by szerwi** [nopnop2002/SC16IS752#10]
Hi,
Can someone explain me how to use interrupts in this expander? I would like to detect changes on digital pins. Does the expander store pin number by which the interrupt was trigerred or do I need to read all the pins and define which pin trigerred the interrupt by myself in Arduino code?

**Comment by nopnop2002** [comment]
There is dataheet.

https://www.nxp.com/docs/en/data-sheet/SC16IS752_SC16IS762.pdf


There is an explanation about I/O Interrupt Enable register in Chapter 8.17.

**Comment by szerwi** [comment]
@nopnop2002 I have read the datasheet, but I don't understand it perfectly. I'm not sure if these registers stor the information about the pin which trigerred the interrupt or not.

**Comment by nopnop2002** [comment]
I tested GPIO input interrupts.

By setting the register, the value of the IIR register at the time of input changes.



However, the value of the IRQ pin does not change.


It monitors the IIR register.

```
i2c_addressr=4d
device found
temp_ier=0
temp_ier=8
temp_ioint=0
mask=4
temp_ioint=4
temp_iir=c1
temp_iir=c1
temp_iir=c1
temp_iir=f0 ---> input pin change of state. But IRQ signal is no change.
temp_iir=c1
temp_iir=c1
temp_iir=f0 ---> input pin change of state. But IRQ signal is no change.
temp_iir=c1
temp_iir=c1

```

**Comment by nopnop2002** [comment]
I added:

https://github.com/nopnop2002/SC16IS752/tree/master/Arduino%20%26%20ESP8266/example/I2C_GPIO_IRQ

https://github.com/nopnop2002/SC16IS752/tree/master/Arduino%20%26%20ESP8266/example/SPI_GPIO_IRQ

**Comment by szerwi** [comment]
Thanks. Shortly after asking this question I've also managed to get the interrupts working.
