### ISSUE TITLE
no Default SDA Pin for Second Peripheral

### ISSUE THREAD

**Issue by edouardreg** [nopnop2002/SC16IS752#14]
Hello,

I'm using the arduino version (nonop2002/sc16s752) with arduino core esp 32 as component (esp-idf 4.4, arduino esp32 master)
The program compilation is OK, but at run time, when it arrives at : 

i2cuart.begin(SC16IS752_DEFAULT_SPEED, SC16IS752_DEFAULT_SPEED);

Those errors appears and the esp32 reboot :

[    56][E][Wire.cpp:77] initPins(): no Default SDA Pin for Second Peripheral
[    57][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[    59][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[    65][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[    72][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[    78][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[    85][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[    91][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[    98][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[   105][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   111][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   117][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   123][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   129][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[   136][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[   143][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   149][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   155][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   161][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   167][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[   174][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   180][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
[   187][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   193][E][esp32-hal-i2c.c:142] i2cWrite(): could not acquire lock
[   199][E][esp32-hal-i2c.c:225] i2cWriteReadNonStop(): could not acquire lock
E (734) Main: I2C_serial not found

Any idea if it's coming from me or from the library ?

Thanks, Ed.

**Comment by nopnop2002** [comment]
This error is occurring inside the core library.

It is better to contact here.

https://github.com/espressif/arduino-esp32/issues
