### ISSUE TITLE
analogWrite

### ISSUE THREAD

**Issue by peter1a** [nopnop2002/SC16IS752#18]
Is in librabry supported https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/ ?

**Comment by nopnop2002** [comment]
SC16IS750/752 does not have the analog write function.

There is a data sheet.

https://www.nxp.com/docs/en/data-sheet/SC16IS740_750_760.pdf

**Comment by peter1a** [comment]
Is not possible in library or HW does not support it?

**Comment by nopnop2002** [comment]
HW does not support it.

Please check the datasheet.

https://www.nxp.com/docs/en/data-sheet/SC16IS740_750_760.pdf
