### ISSUE TITLE
Question on wiring

### ISSUE THREAD

**Issue by garudaonekh** [nopnop2002/SC16IS752#19]
Hi,
My sensor is i2c and i want to convert it to rs485 so that it can connect with my controllers at 20 meter away. But I do not want to use any MCU to convert i2c to RS485.

So I want to connect my i2c sensor to this SC16IS752 and then to UART~RS485(MAX485) module and then to my controller. Does this work?

Thanks

**Comment by nopnop2002** [comment]
Can not do.
This is because SC16IS752 does not have an i2c master function.

**Comment by garudaonekh** [comment]
Thanks
By the way, do you have any suggestion regarding this?

**Comment by nopnop2002** [comment]
>But I do not want to use any MCU to convert i2c to RS485.

You need some kind of MCU with i2c master functionality.


A sample of RS485 is published here.

https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart/uart_echo_rs485

**Comment by garudaonekh** [comment]
Thanks,
I try to avoid MCU but look like impossible.
